### PR TITLE
Adding Narrative on Employee Goals

### PR DESCRIPTION
**Pull request by seamuskraft**

### CODE REVIEW

**Comment by seamuskraft** [comment]
Does this look good to everybody? @krues8dr @cmbirk @abartnick

**Comment by cmbirk** [comment]
@seamuskraft @krues8dr @abartnick we should probably include the Google Doc included here into the repo itself.

**Comment by krusynth** [comment]
I'll translate the document into markdown and post it in one of the repos.

**Comment by krusynth** [comment]
:+1:  Otherwise

**Comment by cmbirk** [comment]
Yep.  Otherwise +1

**Comment by seamuskraft** [comment]
Works for me.  But don't know how to do that (beyond putting in the link I
did).  Could you do that?
- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation http://OpenGovFoundation.org
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov http://twitter.com/foundopengov

**Comment by abartnick** [comment]
+1

**Pull request merged**
