### PR TITLE
Improve anti-discrimination and anti-harassment language.

### PR DESCRIPTION
**Pull request by krusynth**
Changing `sex` to `gender identity, sexual orientation` for more clarity and inclusiveness.  Per http://lgbteeo.github.io/

### CODE REVIEW

**Comment by krusynth** [comment]
@seamuskraft @abartnick @cmbirk  Look good?

**Comment by leahbannon** [comment]
This is a great improvement. :+1: You might also add "gender expression" or even check out the list in the first bullet under this section of 18F's: https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md#boundaries

**Comment by seamuskraft** [comment]
Yes. Thanks Leah (and Bill)!

On Tuesday, May 26, 2015, Bill Hunt notifications@github.com wrote:

> @seamuskraft https://github.com/seamuskraft @abartnick
> https://github.com/abartnick @cmbirk https://github.com/cmbirk Look
> good?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opengovfoundation/hr-manual/pull/2#issuecomment-105709283
> .

## 
- Seamus

---

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation
P: 760-659-0631

## OpenGovFoundation.org

2014/2015 Shuttleworth Fellow

**Comment by krusynth** [comment]
Measure approved by vote.

**Pull request merged**
