### PR TITLE
Updates to Staff, Hours, Meetings

### PR DESCRIPTION
**Pull request by abartnick**
1. Updated staff roster and titles
2. Updated office hours
3. Added daily meeting to Regular Meetings

### CODE REVIEW

**Comment by cmbirk** [comment]
+1

**Comment by abartnick** [comment]
+1

**Comment by krusynth** [comment]
:+1:

@seamuskraft ?

**Comment by seamuskraft** [comment]
Looks great.  Thank you and go for it!

**Comment by seamuskraft** [comment]
[image: :+1:]
- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation http://OpenGovFoundation.org
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov http://twitter.com/foundopengov

**Pull request merged**
